Repository WildCodeSchool/orleans-0218-recipereminder, pull requests merged in 2018-04, with the labels that each got.

#8 S1 nav
  composer.json
  composer.lock
  public/assets/css/styles.css
  public/assets/images/logo-7016.png
  src/View/Admin/admin_header.html.twig
  src/View/Admin/admin_layout.html.twig
  src/View/footer.html.twig
  src/View/header.html.twig
  src/View/layout.html.twig
Labels: Correction Done

#9 S1 homepage mc
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/bgaffiche.jpg
  public/assets/images/popartcook.jpg
  public/assets/images/thumbtest3.jpg
  src/Controller/HomepageController.php
  src/View/Homepage/homepage.html.twig
  src/View/layout.html.twig
  src/View/thumb-event.html.twig
  src/View/thumb-recipe.html.twig
Labels: Correction Done

#7 S1 event
  app/routing.php
  src/Controller/EventController.php
  src/Model/Event.php
  src/Model/EventManager.php
  src/View/Event/eventslist.html.twig
Labels: Correction Done

#10 S1 category
  .gitignore
  app/routing.php
  src/Controller/CategoryController.php
  src/Model/Category.php
  src/Model/CategoryManager.php
  src/View/Admin/Category/category.html.twig
Labels: Correction Done

#31 Dev
  .gitignore
  app/db.php.dist
  app/routing.php
  composer.json
  composer.lock
  public/assets/css/styles.css
  public/assets/images/bgaffiche.jpg
  public/assets/images/logo-7016.png
  public/assets/images/popartcook.jpg
  public/assets/images/thumbtest3.jpg
  src/Controller/CategoryController.php
  src/Controller/EventController.php
  src/Controller/HomepageController.php
  src/Controller/ItemController.php
  src/Controller/RecipeController.php
  src/Model/AbstractManager.php
  src/Model/Category.php
  src/Model/CategoryManager.php
  src/Model/Event.php
  src/Model/EventManager.php
  src/Model/Item.php
  src/Model/Recipe.php
  src/Model/RecipeManager.php
  src/View/Admin/Category/category.html.twig
  src/View/Admin/admin_header.html.twig
  src/View/Admin/admin_layout.html.twig
  src/View/Event/eventslist.html.twig
  src/View/Homepage/homepage.html.twig
  src/View/Recipe/list_recipe.html.twig
  src/View/footer.html.twig
  src/View/header.html.twig
  src/View/layout.html.twig
  src/View/thumb-event.html.twig
  src/View/thumb-recipe.html.twig
Labels: Reviewed by PO

#40 S3 list recipe
  src/Model/AbstractManager.php
  src/Model/Event.php
  src/Model/RecipeManager.php
  src/View/Event/eventslist.html.twig
  src/View/Recipe/list_recipe.html.twig
  src/View/thumb-event.html.twig
  src/View/thumb-recipe.html.twig
Labels: Reviewed by PO

#38 S3 add category
  app/routing.php
  public/assets/css/styles.css
  src/Controller/CategoryController.php
  src/Model/AbstractManager.php
  src/Model/Category.php
  src/Model/EventManager.php
  src/View/Admin/Category/category.html.twig
  src/View/layout.html.twig
Labels: Correction Done

#37 Add recipe s3
  .gitignore
  app/routing.php
  composer.json
  composer.lock
  public/assets/css/styles.css
  public/assets/images/Image5acfc64644e80.png
  public/assets/images/Image5ad0609579608.png
  public/assets/images/Image5ad0612cbb148.png
  public/assets/images/Image5ad06173da77a.png
  src/Controller/RecipeController.php
  src/Model/Recipe.php
  src/Model/UploadManager.php
  src/View/Admin/addRecipe.html.twig
Labels: Correction Done

#39 S3 view recipe
  app/routing.php
  public/assets/css/styles.css
  public/assets/upload/brochettes.jpg
  public/assets/upload/clafoutis.jpg
  public/assets/upload/gateau-chocolat.jpg
  public/assets/upload/grilledfish.jpg
  public/assets/upload/lentilles.jpg
  public/assets/upload/ragout-de-porc.jpg
  public/assets/upload/soupe.jpg
  public/assets/upload/tarte-pomme.jpg
  src/Controller/RecipeController.php
  src/Model/Recipe.php
  src/Model/RecipeManager.php
  src/View/Recipe/show-one-recipe.html.twig
Labels: Correction Done

#42 Add events s3
  app/routing.php
  public/assets/images/Image5acf9c0868319.jpg
  src/Controller/EventController.php
  src/Model/AbstractManager.php
  src/Model/Event.php
  src/Model/UploadManager.php
  src/View/Admin/addEvent.html.twig
  src/View/Admin/admin_header.html.twig
Labels: Correction Done

#45 Bug fix
  src/View/Admin/Category/category.html.twig
  src/View/Admin/Recipe/recipeList.html.twig
Labels: Correction Done

#44 S3 add event
  app/routing.php
  src/Controller/EventController.php
  src/Controller/RecipeController.php
  src/Model/AbstractManager.php
  src/View/Admin/Event/eventList.html.twig
  src/View/Admin/admin_header.html.twig
  src/View/Event/eventList.html.twig
Labels: Correction Done

#77 Dev to master
  src/View/Admin/Event/eventList.html.twig
  src/View/Event/eventList.html.twig
  src/View/thumb-recipe.html.twig
Labels: Reviewed by PO

#52 Last 3 events and last 3 recipes
  app/routing.php
  src/Controller/HomepageController.php
  src/Model/EventManager.php
  src/Model/RecipeManager.php
  src/View/Homepage/homepage.html.twig
  src/View/thumb-event.html.twig
  src/View/thumb-recipe.html.twig
Labels: Correction Done

#76 S4 refonte tableaux
  public/assets/css/styles.css
  public/assets/css/tables.css
  src/View/Admin/Category/category.html.twig
  src/View/Admin/Event/eventList.html.twig
  src/View/Admin/Recipe/recipeList.html.twig
  src/View/Event/eventList.html.twig
  src/View/Recipe/list_recipe.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#71 ajout home page admin
  app/routing.php
  src/Controller/HomepageController.php
  src/View/Admin/adminHomepage.html.twig
  src/View/Admin/admin_header.html.twig
Labels: Correction Done

#81 S4 search recipe
  app/routing.php
  public/assets/css/styles.css
  public/assets/js/script.js
  src/Controller/EventController.php
  src/Controller/RecipeController.php
  src/Model/AbstractManager.php
  src/Model/Category.php
  src/Model/RecipeManager.php
  src/Model/UploadManager.php
  src/View/Admin/Event/addEvent.html.twig
  src/View/Recipe/inc_listRecipe.html.twig
  src/View/Recipe/list_recipe.html.twig
  src/View/layout.html.twig
Labels: Correction Done

#82 Bug fix
   était dans la class
  src/Controller/RecipeController.php
  src/View/Admin/Recipe/recipeList.html.twig
  src/View/Recipe/show-one-recipe.html.twig
Labels: Correction Done

#87 S4 fix css
  public/assets/css/styles.css
  src/View/Admin/admin_header.html.twig
  src/View/Homepage/homepage.html.twig
Labels: Correction Done

#90 Bug fix
  src/Controller/RecipeController.php
  src/View/thumb-event.html.twig
  src/View/thumb-recipe.html.twig
Labels: Reviewed by PO

#94 S4 search recipe admin
  app/routing.php
  public/assets/js/scriptRecipeAdmin.js
  src/Controller/RecipeController.php
  src/View/Admin/Recipe/recipeList.html.twig
  src/View/Admin/Recipe/search_recipeList.html.twig
Labels: Correction Done

#98 ajout navbar fixe petit footer et modification thumb
  public/assets/css/styles.css
  src/View/Admin/admin_header.html.twig
  src/View/footer.html.twig
  src/View/header.html.twig
Labels: Reviewed by PO

#92 S4 search recipe by category
  public/assets/css/styles.css
  public/assets/js/script.js
  public/assets/js/searchRecipe.js
  src/Controller/HomepageController.php
  src/Controller/RecipeController.php
  src/Model/EventManager.php
  src/Model/RecipeManager.php
  src/View/Recipe/list_recipe.html.twig
Labels: Correction Done

#83 Création de la page d'affichage d'un événement
  app/routing.php
  public/assets/css/styles.css
  public/assets/upload/brochettes.jpg
  public/assets/upload/clafoutis.jpg
  public/assets/upload/gateau-chocolat.jpg
  public/assets/upload/grilledfish.jpg
  public/assets/upload/lentilles.jpg
  public/assets/upload/ragout-de-porc.jpg
  public/assets/upload/soupe.jpg
  public/assets/upload/tarte-pomme.jpg
  src/Controller/EventController.php
  src/View/Event/show-one-event.html.twig
  src/View/Recipe/show-one-recipe.html.twig
Labels: Correction Done

#101 S4 bugfix links
  app/config.php
  src/Controller/EventController.php
  src/Controller/RecipeController.php
  src/Model/RecipeManager.php
  src/Model/UploadManager.php
  src/View/Admin/Recipe/addRecipe.html.twig
  src/View/Admin/Recipe/recipeList.html.twig
  src/View/Admin/Recipe/search_recipeList.html.twig
Labels: Reviewed by PO

#104 changement footer et navbar
  public/assets/css/styles.css
  src/View/Admin/Category/category.html.twig
  src/View/Admin/admin_header.html.twig
  src/View/header.html.twig
Labels: Reviewed by PO

#105 bugFix
  src/View/Admin/Category/category.html.twig
  src/View/Admin/Event/eventList.html.twig
  src/View/Admin/Recipe/recipeList.html.twig
  src/View/Admin/adminHomepage.html.twig
  src/View/Admin/admin_layout.html.twig
  src/View/Event/show-one-event.html.twig
  src/View/Recipe/show-one-recipe.html.twig
Labels: Correction Done

#124 Bug fix2
  src/View/Admin/Recipe/recipeList.html.twig
  src/View/Admin/Recipe/show-one-recipe-admin.html.twig
Labels: Reviewed by PO

#128 Add admin event page
  app/routing.php
  src/Controller/EventController.php
  src/View/Admin/Event/show-one-event-admin.html.twig
Labels: Reviewed by PO

#134 changement navbar
  public/assets/css/styles.css
Labels: Reviewed by PO

#146 S5-backToRecipeList-button
  public/assets/css/styles.css
  src/View/Recipe/show-one-recipe.html.twig
Labels: Reviewed by PO

#147 Ajout d'un bouton de retour à la liste des événements sur la page évé…
  src/View/Event/show-one-event.html.twig
Labels: Reviewed by PO

#151 S4 mentions legales
  app/routing.php
  src/Controller/MentionsController.php
  src/View/MentionsLegales/mentions-legales.html.twig
  src/View/footer.html.twig
Labels: Correction Done

#152 mise en place de la recherche d'un évenement par date
  public/assets/js/searchEvent.js
  src/Controller/EventController.php
  src/Model/EventManager.php
  src/View/Event/eventList.html.twig
Labels: Correction Done, Reviewed by PO

#153 S5 pagination
  app/config.php
  public/assets/js/searchRecipe.js
  src/Controller/RecipeController.php
  src/Model/RecipeManager.php
  src/View/Recipe/inc_listRecipe.html.twig
  src/View/Recipe/list_recipe.html.twig
Labels: Correction Done, Reviewed by PO

#155 Deleting an event
  app/routing.php
  src/Controller/EventController.php
  src/View/Admin/Event/show-one-event-admin.html.twig
Labels: Correction Done, Reviewed by PO

#158 Fixed footer
  public/assets/css/styles.css
  src/View/footer.html.twig
Labels: Correction Done, Reviewed by PO

#163 ajout required form
  src/View/Admin/Event/addEvent.html.twig
  src/View/Admin/Recipe/addRecipe.html.twig
Labels: Reviewed by PO

#164 S5 delete category
  app/routing.php
  public/assets/css/styles.css
  src/Controller/CategoryController.php
  src/View/Admin/Category/category.html.twig
Labels: Reviewed by PO

#162 S4 update event
  app/routing.php
  public/assets/css/styles.css
  src/Controller/EventController.php
  src/Controller/RecipeController.php
  src/Model/AbstractManager.php
  src/Model/EventManager.php
  src/Model/UploadManager.php
  src/View/Admin/Event/updateEvent.html.twig
  src/View/Admin/Recipe/updateRecipe.html.twig
Labels: Correction Done, Reviewed by PO

#161 intégration du systeme de infiniteScroll pour les event
  public/assets/js/searchEvent.js
  src/Controller/EventController.php
  src/Model/EventManager.php
  src/View/Event/eventList.html.twig
  src/View/Event/inc_listEvent.html.twig
Labels: Correction Done

#166 S5 bugfix2
  public/assets/css/recipe-event.css
  public/assets/css/styles.css
  public/assets/css/tables.css
  src/Model/UploadManager.php
  src/View/Admin/Event/show-one-event-admin.html.twig
  src/View/Admin/Recipe/recipeList.html.twig
  src/View/Admin/Recipe/show-one-recipe-admin.html.twig
  src/View/Event/show-one-event.html.twig
  src/View/Recipe/show-one-recipe.html.twig
Labels: Correction Done, Reviewed by PO

#168 S5 update category
  app/routing.php
  public/assets/js/updateCategory.js
  src/Controller/CategoryController.php
  src/View/Admin/Category/category.html.twig
Labels: Correction Done, Reviewed by PO

#175 S5bug fix raph
  app/routing.php
  public/assets/css/styles.css
  src/Controller/GeneralConditionsController.php
  src/Controller/MentionsController.php
  src/View/Admin/Event/show-one-event-admin.html.twig
  src/View/Event/eventList.html.twig
  src/View/Event/show-one-event.html.twig
  src/View/GeneralConditions/general-conditions.html.twig
  src/View/Recipe/show-one-recipe.html.twig
Labels: Reviewed by PO

#173 intégration du systeme de recherche coté admin
  app/routing.php
  public/assets/js/searchEvent.js
  src/Controller/EventController.php
  src/Model/EventManager.php
  src/View/Admin/Event/eventList.html.twig
  src/View/Admin/Event/search_eventList.html.twig
Labels: Correction Done

#176 bug fix event
  public/assets/js/searchEvent.js
  src/Controller/EventController.php
  src/View/Event/eventList.html.twig
Labels: Reviewed by PO

#177 Bug fix yoan
  public/assets/js/updateCategory.js
  src/Controller/CategoryController.php
  src/Model/AbstractManager.php
  src/View/Admin/Category/category.html.twig
Labels: Reviewed by PO

#178 S5 accroche
  app/routing.php
  public/assets/css/styles.css
  public/assets/js/catchPhrase.js
  src/Controller/CompanyController.php
  src/Controller/HomepageController.php
  src/Model/Company.php
  src/Model/CompanyManager.php
  src/View/Admin/adminHomepage.html.twig
  src/View/Homepage/homepage.html.twig
Labels: Reviewed by PO

#170 S5 link recipes to one event
  app/routing.php
  public/assets/css/styles.css
  public/assets/js/linkRecipesToOneEvent.js
  public/assets/js/searchRecipeToLink.js
  src/Controller/EventController.php
  src/Model/Event.php
  src/Model/EventRecipe.php
  src/Model/EventRecipeManager.php
  src/View/Admin/Event/searchRecipeToLink.html.twig
  src/View/Admin/Event/show-one-event-admin.html.twig
Labels: Correction Done, Reviewed by PO

#179 S5 update recipe
  src/Controller/RecipeController.php
  src/Model/AbstractManager.php
  src/Model/RecipeManager.php
  src/View/Admin/Event/updateEvent.html.twig
  src/View/Admin/Recipe/show-one-recipe-admin.html.twig
  src/View/Admin/Recipe/updateRecipe.html.twig
Labels: Correction Done, Reviewed by PO

#180 creation button modifier un event
  src/View/Admin/Event/show-one-event-admin.html.twig
Labels: Correction Done, Reviewed by PO

#181 Bug fix yoan
  src/Model/EventManager.php
Labels: Reviewed by PO

#182 Bug fix css
  public/assets/css/recipe-event.css
  src/View/Admin/Event/eventList.html.twig
Labels: Reviewed by PO

#183 Lastfixbug
  src/View/Admin/Event/show-one-event-admin.html.twig
Labels: Reviewed by PO
