Repository WildCodeSchool/orleans-0218-recipereminder, pull requests merged in 2018-05, with the labels that each got.

#192 bug fix + page 404
  app/Connection.php
  app/dispatcher.php
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/wallpaper_section.png
  src/Controller/ErrorsController.php
  src/View/Errors/error404.html.twig
  src/View/Recipe/show-one-recipe.html.twig
Labels: Correction Done

#193 S6 unlink recipe from one event
  app/routing.php
  public/assets/css/recipe-event.css
  public/assets/css/styles.css
  public/assets/js/searchRecipeToLink.js
  src/Controller/EventController.php
  src/Controller/RecipeController.php
  src/Model/EventRecipeManager.php
  src/View/Admin/Event/show-one-event-admin.html.twig
  src/View/Admin/Recipe/show-one-recipe-admin.html.twig
  src/View/Admin/thumb-event-admin.html.twig
  src/View/Admin/thumb-recipe-admin.html.twig
  src/View/Recipe/show-one-recipe.html.twig
Labels: Reviewed by PO

#195 le phrase d'accroche ne peut plus être enregistrée vide.
  public/assets/js/catchPhrase.js
  src/Controller/CompanyController.php
  src/Model/RecipeManager.php
Labels: Reviewed by PO

#197 S6 update recipe
  src/Controller/RecipeController.php
Labels: Reviewed by PO

#194 S6 link events to one recipe
  app/routing.php
  public/assets/js/linkEventsToOneRecipe.js
  public/assets/js/searchEvent.js
  src/Controller/RecipeController.php
  src/Model/EventRecipeManager.php
  src/View/Admin/Event/searchRecipeToLink.html.twig
  src/View/Admin/Recipe/searchEventToLink.html.twig
  src/View/Admin/Recipe/show-one-recipe-admin.html.twig
Labels: Correction Done

#196 S6 issue edit img
  public/assets/css/edit-recipe-event.css
  public/assets/css/styles.css
  src/Controller/EventController.php
  src/View/Admin/Event/updateEvent.html.twig
  src/View/Admin/Recipe/updateRecipe.html.twig
  src/View/footer.html.twig
Labels: Reviewed by PO

#199 corrections bug update
  src/Controller/RecipeController.php
  src/View/Admin/Recipe/updateRecipe.html.twig
Labels: Correction Done, Reviewed by PO

#200 Delete était dans la class
   était dans la class
Labels: Correction Done, Reviewed by PO

#198 Bug fix yoan
  app/routing.php
  public/assets/css/styles.css
  public/assets/js/category.js
  public/assets/js/searchEvent.js
  public/assets/js/searchRecipe.js
  public/assets/js/updateCategory.js
  src/Controller/CategoryController.php
  src/Model/RecipeManager.php
  src/Model/UploadManager.php
  src/View/Admin/Category/category.html.twig
  src/View/Admin/Category/nbRecipe.html.twig
Labels: Correction Done, Reviewed by PO

#205 Bugfix please
  src/Controller/RecipeController.php
  src/View/Admin/Event/updateEvent.html.twig
Labels: Correction Done, Reviewed by PO

#204 Dev
   était dans la class
  app/Connection.php
  app/dispatcher.php
  app/routing.php
  public/assets/css/edit-recipe-event.css
  public/assets/css/recipe-event.css
  public/assets/css/styles.css
  public/assets/images/wallpaper_section.png
  public/assets/js/catchPhrase.js
  public/assets/js/category.js
  public/assets/js/linkEventsToOneRecipe.js
  public/assets/js/searchEvent.js
  public/assets/js/searchRecipe.js
  public/assets/js/searchRecipeToLink.js
  public/assets/js/updateCategory.js
  src/Controller/CategoryController.php
  src/Controller/CompanyController.php
  src/Controller/ErrorsController.php
  src/Controller/EventController.php
  src/Controller/RecipeController.php
  src/Model/EventRecipeManager.php
  src/Model/RecipeManager.php
  src/Model/UploadManager.php
  src/View/Admin/Category/category.html.twig
  src/View/Admin/Category/nbRecipe.html.twig
  src/View/Admin/Event/searchRecipeToLink.html.twig
  src/View/Admin/Event/show-one-event-admin.html.twig
  src/View/Admin/Event/updateEvent.html.twig
  src/View/Admin/Recipe/searchEventToLink.html.twig
  src/View/Admin/Recipe/show-one-recipe-admin.html.twig
  src/View/Admin/Recipe/updateRecipe.html.twig
  src/View/Admin/thumb-event-admin.html.twig
  src/View/Admin/thumb-recipe-admin.html.twig
  src/View/Errors/error404.html.twig
  src/View/Event/show-one-event.html.twig
  src/View/Recipe/show-one-recipe.html.twig
  src/View/footer.html.twig
Labels: Correction Done, Reviewed by PO

#207 last modif' redirection updateEvent
  src/Controller/EventController.php
  src/View/Admin/Category/category.html.twig
Labels: Reviewed by PO

#206 Codesniffer
  app/routing.php
  src/Controller/CategoryController.php
  src/Controller/CompanyController.php
  src/Controller/ErrorsController.php
  src/Controller/EventController.php
  src/Controller/HomepageController.php
  src/Controller/RecipeController.php
  src/Model/AbstractManager.php
  src/Model/CompanyManager.php
  src/Model/Event.php
  src/Model/EventManager.php
  src/Model/EventRecipe.php
  src/Model/EventRecipeManager.php
  src/Model/Recipe.php
  src/Model/RecipeManager.php
  src/Model/UploadManager.php
  src/View/Admin/Event/show-one-event-admin.html.twig
  src/View/Admin/Recipe/show-one-recipe-admin.html.twig
  src/View/Admin/thumb-event-admin.html.twig
  src/View/Admin/thumb-recipe-admin.html.twig
Labels: Correction Done, Reviewed by PO

#208 Dev
  app/routing.php
  src/Controller/CategoryController.php
  src/Controller/CompanyController.php
  src/Controller/ErrorsController.php
  src/Controller/EventController.php
  src/Controller/HomepageController.php
  src/Controller/RecipeController.php
  src/Model/AbstractManager.php
  src/Model/CompanyManager.php
  src/Model/Event.php
  src/Model/EventManager.php
  src/Model/EventRecipe.php
  src/Model/EventRecipeManager.php
  src/Model/Recipe.php
  src/Model/RecipeManager.php
  src/Model/UploadManager.php
  src/View/Admin/Category/category.html.twig
  src/View/Admin/Event/show-one-event-admin.html.twig
  src/View/Admin/Recipe/show-one-recipe-admin.html.twig
  src/View/Admin/thumb-event-admin.html.twig
  src/View/Admin/thumb-recipe-admin.html.twig
Labels: Reviewed by PO
